# Introduction

**NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements. NumPy provides various powerful data structures, implementing multi-dimensional arrays and matrices. These data structures are used for the optimal computations regarding arrays and matrices.**

**Travis Oliphant** created NumPy package in 2005 by injecting the features of the ancestor module Numeric into another module Numarray. It is an extension module of Python which is mostly written in C. It provides various functions which are capable of performing the numeric computations with a high speed.

# NumPy Tutorial 🐠

The numpy is a popular Python library that is provided as 3rd party. The numpy provides an array, lists related operations in an easy-use way. In order to use it we have to install and import it .

**Import numpy**

The numpy should be imported in order to use it. It can be imported by using the import statement and module name like below.

In [2]:
import numpy 

But typing the numpy every time we use one of the elements of numpy is not a practical way. So Python provides the alias which can be used to create alias which is generally a shorter name for the specified module. The following import statement can be used with the “as” statement in order to create alias “np” for the numpy.

In [3]:
import numpy as np

# To Check numpy version 

print(np.__version__)

1.19.5


# NumPy Ndarray

Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. In other words, we can define a ndarray as the collection of the data type (dtype) objects.

The ndarray object can be accessed by using the 0 based indexing. Each element of the Array object contains the same size in the memory.

*Syntax to create Ndarray is given below.*

**numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)**



In [4]:
# Creating One Ddimensional  array
import numpy as np

a=np.array([3,6,32,7])
print("One dimensional array a =",a)

One dimensional array a = [ 3  6 32  7]


In [5]:
# Creating Two Dimensional array 
import numpy as np

b=np.array([[1,2,3],[4,7,6]])
print("Two dimensional array b= \n",b)

Two dimensional array b= 
 [[1 2 3]
 [4 7 6]]


**The features of ndarray are as follows :**

* **ndarray.ndim** : the dimension number of the array. It's called rank in Python.
* **ndarray.shape** : the dimension of the array. It's a series of numbers whose length is determined by the dimension （ndim） of the array. 
    For example, the shape of a one-dimensional array with length n is n. And the shape of an array with n rows and m columns is n,m.
* **ndarray.size** : the number of all elements in the array.
* **ndarray.dtype** : the type of the element in the array, such as numpy.int32, numpy.int16, or numpy.float64.
* **ndarray.itemsize** : the size of each element in the array, in bytes.


**Let's take a look at the code example**

In [6]:
# Finding the dimensions of the Array
import numpy as np 

arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [9, 10, 11, 23]]) 
print(arr)
c=arr.ndim  
print("The dimension of array arr is ",c)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 9 10 11 23]]
The dimension of array arr is  2


In [7]:
# Finding the size of each array element
import numpy as np  

c = np.array([[1,2,3 ,85 ,78]])  
print("Each item contains",c.itemsize,"bytes")  

Each item contains 8 bytes


In [8]:
# Finding the data type of each array item
import numpy as np  

c = np.array([[1,2,3]])  
print("Each item is of the type",c.dtype)  

Each item is of the type int64


In [9]:
# Finding the shape and size of the array
import numpy as np  

c = np.array([[1,2,3,4,5,6,7]])  
print("Array Size:",c.size)  
print("Shape:",c.shape)  

Array Size: 7
Shape: (1, 7)


# NumPy dtype

A data type object describes interpretation of fixed block of memory corresponding to an array, depending on the following aspects −

* Type of data (integer, float or Python object)

* Size of data

* Byte order (little-endian or big-endian)

* In case of structured type, the names of fields, data type of each field and part of the memory block taken by each field.

* If data type is a subarray, its shape and data type

The byte order is decided by prefixing '<' or '>' to data type. '<' means that encoding is little-endian (least significant is stored in smallest address). '>' means that encoding is big-endian (most significant byte is stored in smallest address).


*We can create a dtype object by using the following syntax.*

**numpy.dtype(object, align, copy)**




**Data Types & Description**
 
1	**bool_ :** Boolean (True or False) stored as a byte

2	**int_ :** Default integer type (same as C long; normally either int64 or int32)

3	**intc :** Identical to C int (normally int32 or int64)

4	**intp :** Integer used for indexing (same as C ssize_t; normally either int32 or int64)

5	**int8 :** Byte (-128 to 127)

6	**int16 :** Integer (-32768 to 32767)

7	**int32 :** Integer (-2147483648 to 2147483647)

8	**int64 :** Integer (-9223372036854775808 to 9223372036854775807)

9	**uint8 :** Unsigned integer (0 to 255)

10	**uint16 :** Unsigned integer (0 to 65535)

11	**uint32 :** Unsigned integer (0 to 4294967295)

12	**uint64 :** Unsigned integer (0 to 18446744073709551615)

13	**float_ :** Shorthand for float64

14	**float16 :** Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

15	**float32 :** Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

16	**float64 :** Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

17	**complex_ :** Shorthand for complex128

18	**complex64 :** Complex number, represented by two 32-bit floats (real and imaginary components)

19	**complex128 :** Complex number, represented by two 64-bit floats (real and imaginary components)


In [10]:
# using array-scalar type 
import numpy as np 

d= np.dtype(np.int32) 
print(d)

int32


In [11]:
# Note : int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 

d = np.dtype('i4')
print (d) 


int32


In [12]:
# using endian notation 
import numpy as np 

d = np.dtype('>i4') 
print(d)

>i4


In [13]:
# first create structured data type 
import numpy as np 

d = np.dtype([('age',np.int8)]) 
print(d) 

[('age', 'i1')]


The following examples show the use of structured data type. Here, the field name and the corresponding scalar data type is to be declared.

In [14]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)

[(10,) (20,) (30,)]


In [15]:
# file name can be used to access content of age column 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a['age'])


[10 20 30]


The following examples define a structured data type called student with a string field 'name', an integer field 'age' and a float field 'marks'. This dtype is applied to ndarray object.

In [16]:
import numpy as np 

student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [17]:
import numpy as np 

student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


# Numpy Array Creation

The ndarray object can be constructed by using the following routines.

* **Numpy.empty**

 As the name specifies, The empty routine is used to create an uninitialized array of specified shape and data type.

 *The syntax is given below.*

 **numpy.empty(shape, dtype = float, order = 'C')**

In [18]:
import numpy as np  

arr = np.empty((3,2), dtype = int)  
print(arr)  

[[94159916307904              0]
 [             0              0]
 [             0              0]]


* **NumPy.Zeros**

 This routine is used to create the numpy array with the specified shape where each numpy array item is initialized to 0.

 *The syntax is given below.*

 **numpy.zeros(shape, dtype = float, order = 'C')**  

In [19]:
import numpy as np  

arr = np.zeros((3,2), dtype = int)  
print(arr)  

[[0 0]
 [0 0]
 [0 0]]


* **NumPy.ones**

 This routine is used to create the numpy array with the specified shape where each numpy array item is initialized to 1.

 *The syntax to use this module is given below.*

 **numpy.ones(shape, dtype = none, order = 'C')**  

In [20]:
import numpy as np  

arr = np.ones((3,2), dtype = int)  
print(arr)  

[[1 1]
 [1 1]
 [1 1]]


# Numpy array from existing data

NumPy provides us the way to create an array by using the existing data.

* **Numpy.asarray**

 This routine is used to create an array by using the existing data in the form of lists, or tuples. This routine is useful in the scenario where we need to convert a python sequence into the numpy array object.

 *The syntax to use the asarray() routine is given below.*

 **numpy.asarray(sequence,  dtype = None, order = None)**  

In [21]:
# Creating numpy array using the list
import numpy as np 

l=[1,2,3,4,5,6,7]  
a = np.asarray(l);  
print(type(a))  
print(a)  

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [22]:
# Creating a numpy array using Tuple
import numpy as np 

l=(1,2,3,4,5,6,7)     
a = np.asarray(l);  
print(type(a))  
print(a)  

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [23]:
# Creating a numpy array using more than one list
import numpy as np  

l=[[1,2,3,4,5,6,7],[8,9]]  
a = np.asarray(l);  
print(type(a))  
print(a)  

<class 'numpy.ndarray'>
[list([1, 2, 3, 4, 5, 6, 7]) list([8, 9])]


/opt/conda/lib/python3.7/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [24]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print(a) 

[(1, 2, 3) (4, 5)]


* **Numpy.frombuffer**

 This function is used to create an array by using the specified buffer. 

 *The syntax to use this buffer is given below.*

 **numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)**  

In [25]:
import numpy as np  

l = b'Detailed Numpy Tutorial '  
print(type(l))  
a = np.frombuffer(l, dtype = "S1")  
print(a)  
print(type(a))  

<class 'bytes'>
[b'D' b'e' b't' b'a' b'i' b'l' b'e' b'd' b' ' b'N' b'u' b'm' b'p' b'y'
 b' ' b'T' b'u' b't' b'o' b'r' b'i' b'a' b'l' b' ']
<class 'numpy.ndarray'>


* **Numpy.fromiter**

 This routine is used to create a ndarray by using an iterable object. It returns a one-dimensional ndarray object.

 *The syntax is given below.*

 **numpy.fromiter(iterable, dtype, count = - 1)**  

In [26]:
import numpy as np 

list = [0,2,4,6]  
a = iter(list)  
x = np.fromiter(a, dtype = float)  
print(x)  
print(type(x))  

[0. 2. 4. 6.]
<class 'numpy.ndarray'>


In [27]:
# obtain iterator object from list 
import numpy as np 

list = range(5) 
it = iter(list)  

# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print(x)

[0. 1. 2. 3. 4.]


# Numpy Arrays within the numerical range

This section of the tutorial illustrates how the numpy arrays can be created using some given specified range.

* **Numpy.arrange**

 It creates an array by using the evenly spaced values over the given interval. 

 *The syntax to use the function is given below.*

 **numpy.arrange(start, stop, step, dtype)**


In [28]:
import numpy as np 

x = np.arange(5) 
print(x)

[0 1 2 3 4]


In [29]:
# start and stop parameters set 
import numpy as np 

arr = np.arange(0,10,2,float)  
print(arr)  

[0. 2. 4. 6. 8.]


In [30]:
import numpy as np  

arr = np.arange(10,100,5,int)  
print("The array over the given range is ",arr)  

The array over the given range is  [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


* **NumPy.linspace**

 It is similar to the arrange function. However, it doesn't allow us to specify the step size in the syntax. Instead of that, it only returns evenly separated values over a specified period. The system implicitly calculates the step size.

 *The syntax is given below.*

 **numpy.linspace(start, stop, num, endpoint, retstep, dtype)**   

In [31]:
import numpy as np  

arr = np.linspace(10, 20, 5)  
print("The array over the given range is ",arr)  

The array over the given range is  [10.  12.5 15.  17.5 20. ]


In [32]:
# endpoint set to false 
import numpy as np  

arr = np.linspace(10, 20, 5, endpoint = False)  
print("The array over the given range is ",arr) 

The array over the given range is  [10. 12. 14. 16. 18.]


In [33]:
# find retstep value 
import numpy as np 

x = np.linspace(1,2,5, retstep = True) 
print (x) 
# retstep here is 0.25

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


* **Numpy.logspace**

 It creates an array by using the numbers that are evenly separated on a log scale.

 *The syntax is given below.*

 **numpy.logspace(start, stop, num, endpoint, base, dtype)**  

In [34]:
import numpy as np

arr = np.logspace(10, 20, num = 5, endpoint = True)  
print("The array over the given range is ",arr)

The array over the given range is  [1.00000000e+10 3.16227766e+12 1.00000000e+15 3.16227766e+17
 1.00000000e+20]


In [35]:
# set base of log space to 2
import numpy as np  

arr = np.logspace(10, 20, num = 5,base = 2, endpoint = True)  
print("The array over the given range is ",arr)

The array over the given range is  [1.02400000e+03 5.79261875e+03 3.27680000e+04 1.85363800e+05
 1.04857600e+06]


# NumPy - Indexing & Slicing

As mentioned earlier, items in ndarray object follows zero-based index. Three types of indexing methods are available − field access, **basic slicing** and **advanced indexing** .

**Basic slicing** is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of 

In [36]:
import numpy as np 

a = np.arange(10) 
s = slice(2,7,2) 
print (a[s])


[2 4 6]


In the above example, an ndarray object is prepared by arange() function. Then a slice object is defined with start, stop, and step values 2, 7, and 2 respectively. When this slice object is passed to the ndarray, a part of it starting with index 2 up to 7 with a step of 2 is sliced.

The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object.

In [37]:
import numpy as np 

a = np.arange(10) 
b = a[2:7:2] 
print(b)

[2 4 6]


If only one parameter is put, a single item corresponding to the index will be returned. If a : is inserted in front of it, all items from that index onwards will be extracted. If two parameters (with : between them) is used, items between the two indexes (not including the stop index) with default step one are sliced.

In [38]:
# slice single item 
import numpy as np 

a = np.arange(10) 
b = a[5] 
print(b)

5


In [39]:
# slice items starting from index 
import numpy as np 

a = np.arange(10) 
print(a[2:])

[2 3 4 5 6 7 8 9]


In [40]:
# slice items between indexes 
import numpy as np 

a = np.arange(10) 
print(a[2:5])

[2 3 4]


In [41]:
import numpy as np 

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)  

# slice items starting from index
print('Now we will slice the array from the index a[1:]') 
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [42]:
# array to begin with 
import numpy as np 

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:') 
print(a) 
print('\n')  

# this returns array of items in the second column 
print('The items in the second column are:'  )
print(a[...,1] )
print('\n')  

# Now we will slice all items from the second row 
print('The items in the second row are:' )
print(a[1,...]) 
print( '\n'  )

# Now we will slice all items from column 1 onwards 
print('The items column 1 onwards are:') 
print(a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


# NumPy - Advanced Indexing

It is possible to make a selection from ndarray that is a non-tuple sequence, ndarray object of integer or Boolean data type, or a tuple with at least one item being a sequence object. Advanced indexing always returns a copy of the data. As against this, the slicing only presents a view.

There are two types of advanced indexing − **Integer** and **Boolean.**

* **Integer Indexing**

 This mechanism helps in selecting any arbitrary item in an array based on its Ndimensional index. Each integer array represents the number of indexes into that dimension. When the index consists of as many integer arrays as the dimensions of the target ndarray, it becomes straightforward.


In the following example, one element of specified column from each row of ndarray object is selected. Hence, the row index contains all row numbers, and the column index specifies the element to be selected.

In [43]:
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print(y)

[1 4 5]


The selection includes elements at (0,0), (1,1) and (2,0) from the first array.

In the following example, elements placed at corners of a 4X3 array are selected. The row indices of selection are [0, 0] and [3,3] whereas the column indices are [0,2] and [0,2].

In [44]:
import numpy as np 

x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Original error  array is') 
print(x) 
print('\n') 

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print('The corner elements of this array are:') 
print (y)

Original error  array is
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


Advanced and basic indexing can be combined by using one slice (:) or ellipsis (…) with an index array. The following example uses slice for row and advanced index for column. The result is the same when slice is used for both. But advanced index results in copy and may have different memory layout.

In [45]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print ('Original array') 
print (x) 
print ('\n')  

# slicing 
z = x[1:4,1:3] 

print ('After slicing, our array becomes:' )
print (z)
print ('\n')  

# using advanced index for column 

y = x[1:4,[1,2]] 

print ('Slicing using advanced index for column:') 
print(y)


Original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]


Slicing using advanced index for column:
[[ 4  5]
 [ 7  8]
 [10 11]]


# Boolean Array Indexing

This type of advanced indexing is used when the resultant object is meant to be the result of Boolean operations, such as comparison operators.


In [46]:
# This example, items greater than 5 are returned as a result of Boolean indexing.
import numpy as np 

x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print('Orginal array is') 
print(x)
print('\n')  

# Now we will print the items greater than 5 
print('The items greater than 5 are:') 
print(x[x > 5])


Orginal array is
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]


In [47]:
# This example shows how to filter out the non-complex elements from an array.
import numpy as np 

a = np.array([1, 2+6j, 5, 3.5+5j]) 
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


# NumPy Broadcasting

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [48]:
import numpy as np

a = np.array([1,2,3,4,5,6,7])  
b = np.array([2,4,6,8,10,12,8])  
c= np.multiply(a,b)  
print(c)  

[ 2  8 18 32 50 72 56]


In [49]:
import numpy as np 

a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])  

print("\nprinting array a..")  
print(a)  

print("\nprinting array b..")  

print(b)  

print("\nAdding arrays a and b ..")  
c = a + b
print(c)  


printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b..
[2 4 6 8]

Adding arrays a and b ..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


# NumPy Array Iteration

NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

**Order of Iteration**

There are two ways of storing values into the numpy arrays:

* **F-style order**
* **C-style order**

In [50]:
#Let us create a 3X4 array using arange() function and iterate over it using nditer.
import numpy as np  

a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]]) 

print("Original array:")  
print(a)

print("Iterating over the array:")  
for x in np.nditer(a):  
    print(x,end=' ')  

Original array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]
Iterating over the array:
1 2 3 4 2 4 5 6 10 20 39 3 

In [51]:
#Let's see an example of how the numpy Iterator treats the specific orders (F or C).
import numpy as np  
  
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
  
print("\nPrinting the array:\n")  
  
print(a)  
  
print("\nPrinting the transpose of the array:\n")  
at = a.T  
  
print(at)  
  
print("\nIterating over the transposed array\n")  
  
for x in np.nditer(at):  
    print(x, end= ' ')  
  
 
print("\nIterating over the C-style array:\n")  
c = at.copy(order = 'C')  
for x in np.nditer(c):  
    print(x,end=' ')  
      
d = at.copy(order = 'F')  
  
print(d)  
print("Iterating over the F-style array:\n")  
for x in np.nditer(d):  
    print(x,end=' ')  


Printing the array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Printing the transpose of the array:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the transposed array

1 2 3 4 2 4 5 6 10 20 39 3 
Iterating over the C-style array:

1 2 10 2 4 20 3 5 39 4 6 3 [[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]
Iterating over the F-style array:

1 2 3 4 2 4 5 6 10 20 39 3 

In [52]:
# We can mention the order 'C' or 'F' while defining the Iterator object itself. let's Consider the an example.
import numpy as np  
  
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
  
print("\nPrinting the array:\n")  
  
print(a)  
  
print("\nPrinting the transpose of the array:\n")  
at = a.T  
  
print(at)  
  
print("\nIterating over the transposed array\n")  
  
for x in np.nditer(at):  
    print(x, end= ' ')  

print("\nIterating over the C-style array:\n")  
for x in np.nditer(at, order = 'C'):  
    print(x,end=' ')  



Printing the array:

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

Printing the transpose of the array:

[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]

Iterating over the transposed array

1 2 3 4 2 4 5 6 10 20 39 3 
Iterating over the C-style array:

1 2 10 2 4 20 3 5 39 4 6 3 

# NumPy Mathematical Functions

Numpy contains a large number of mathematical functions which can be used to perform various mathematical operations. The mathematical functions include trigonometric functions, arithmetic functions, and functions for handling complex numbers. Let's discuss the mathematical functions.



* **Trigonometric functions**

 Numpy contains the trigonometric functions which are used to calculate the sine, cosine, and tangent of the different angles in radian

In [53]:
import numpy as np  

arr = np.array([0, 30, 60, 90, 120, 150, 180])  

print("\nThe sin value of the angles",end = " ")  
print(np.sin(arr * np.pi/180)) 

print("\nThe cosine value of the angles",end = " ")  
print(np.cos(arr * np.pi/180))

print("\nThe tangent value of the angles",end = " ")  
print(np.tan(arr * np.pi/180))  


The sin value of the angles [0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]

The cosine value of the angles [ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]

The tangent value of the angles [ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


* **Rounding Functions**

 The numpy provides various functions that can be used to truncate the value of a decimal float number rounded to a particular precision of decimal numbers. Let's discuss the rounding functions.
 
 *  **The numpy.around() function**
 
   This function returns a decimal value rounded to a desired position of the decimal. 

   *The syntax of the function is given below.*

   **numpy.around(num, decimals)**


In [54]:
import numpy as np  
arr = np.array([12.202, 90.23120, 123.020, 23.202])  

print("printing the original array values:",end = " ")  
print(arr)  

print("Array values rounded off to 2 decimal position",np.around(arr, 2))  

print("Array values rounded off to -1 decimal position",np.around(arr, -1))

printing the original array values: [ 12.202   90.2312 123.02    23.202 ]
Array values rounded off to 2 decimal position [ 12.2   90.23 123.02  23.2 ]
Array values rounded off to -1 decimal position [ 10.  90. 120.  20.]


* **Numpy.floor() function**

 This function is used to return the floor value of the input data which is the largest integer not greater than the input value.

In [55]:
# Let consider the following example.
import numpy as np  

arr = np.array([12.202, 90.23120, 123.020, 23.202])  
print(np.floor(arr))  


[ 12.  90. 123.  23.]


* **Numpy.ceil() function**

 This function is used to return the ceiling value of the array values which is the smallest integer value greater than the array elements

In [56]:
# Let consider the following example.
import numpy as np 

arr = np.array([12.202, 90.23120, 123.020, 23.202])  
print(np.ceil(arr))  

[ 13.  91. 124.  24.]


# Numpy statistical functions

Numpy provides various statistical functions which are used to perform some statistical data analysis

* **Finding the minimum and maximum elements from the array**

 The numpy.amin() and numpy.amax() functions are used to find the minimum and maximum of the array elements along the specified axis respectively.

In [57]:
import numpy as np  
  
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("The original array:\n")  
print(a)  

# Maximum and Minimum  
print("\nThe minimum element among the array:",np.amin(a))  
print("The maximum element among the array:",np.amax(a))  
  
# Maximum and Minimum along axis 0 
print("\nThe minimum element among the rows of array",np.amin(a,0))  
print("The maximum element among the rows of array",np.amax(a,0))  
  
# Maximum and Minimum along axis 1
print("\nThe minimum element among the columns of array",np.amin(a,1))  
print("The maximum element among the columns of array",np.amax(a,1))  


# Note axis 0 represent row and axis 1 represent columun

The original array:

[[ 2 10 20]
 [80 43 31]
 [22 43 10]]

The minimum element among the array: 2
The maximum element among the array: 80

The minimum element among the rows of array [ 2 10 10]
The maximum element among the rows of array [80 43 31]

The minimum element among the columns of array [ 2 31 10]
The maximum element among the columns of array [20 80 43]


* **Numpy.ptp() function**
 
 The name of the function numpy.ptp() is derived from the name peak-to-peak. It is used to return the range of values along an axis

In [58]:
# Let consider the following example.

import numpy as np  
  
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("Original array:\n",a)  
  
print("\nptp value along axis 1:",np.ptp(a,1))  
  
print("ptp value along axis 0:",np.ptp(a,0)) 

Original array:
 [[ 2 10 20]
 [80 43 31]
 [22 43 10]]

ptp value along axis 1: [18 49 33]
ptp value along axis 0: [78 33 21]


* **Numpy.percentile() function**
 
 The syntax to use the function is : numpy.percentile(input, q, axis)


In [59]:
import numpy as np  
  
a = np.array([[2,10,20],[80,43,31],[22,43,10]])  
  
print("Array:\n",a)  
  
print("\nPercentile along axis 0",np.percentile(a, 10,0))  
  
print("Percentile along axis 1",np.percentile(a, 10, 1)) 

Array:
 [[ 2 10 20]
 [80 43 31]
 [22 43 10]]

Percentile along axis 0 [ 6.  16.6 12. ]
Percentile along axis 1 [ 3.6 33.4 12.4]


In [60]:
# Calculating median, mean, and average of array items
import numpy as np  
  
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
  
print("Array:\n",a)  
  
print("\nMedian of array along axis 0:",np.median(a,0))  

print("Mean of array along axis 0:",np.mean(a,0))  

print("Average of array along axis 1:",np.average(a,1))  

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Median of array along axis 0: [4. 5. 6.]
Mean of array along axis 0: [4. 5. 6.]
Average of array along axis 1: [2. 5. 8.]


In [61]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:') 
print(a) 
print('\n')  

print('Applying mean() function:') 
print( np.mean(a)) 
print('\n')  

# along axis 0
print('Applying mean() function along axis 0:') 
print(np.mean(a, axis = 0)) 
print('\n') 

# along axis 1
print('Applying mean() function along axis 1:') 
print(np.mean(a, axis = 1))

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Applying mean() function:
3.6666666666666665


Applying mean() function along axis 0:
[2.66666667 3.66666667 4.66666667]


Applying mean() function along axis 1:
[2. 4. 5.]


# NumPy Sorting and Searching

Numpy provides a variety of functions for sorting and searching. There are various sorting algorithms like quicksort, merge sort and heapsort which is implemented using the numpy.sort() function.

*The syntax to use the numpy.sort() function is given below*.

**numpy.sort(a, axis, kind, order)**  

In [62]:
import numpy as np  
  
a = np.array([[10,2,3],[4,5,6],[7,8,9]])  
  
print("Sorting along the columns:")  
print(np.sort(a))  
  
print("Sorting along the rows:")  
print(np.sort(a, 0))  
  
data_type = np.dtype([('name', 'S10'),('marks',int)])  
  
arr = np.array([('Mukesh',200),('John',251)],dtype = data_type)  
  
print("Sorting data ordered by name")  
  
print(np.sort(arr,order = 'name'))  

Sorting along the columns:
[[ 2  3 10]
 [ 4  5  6]
 [ 7  8  9]]
Sorting along the rows:
[[ 4  2  3]
 [ 7  5  6]
 [10  8  9]]
Sorting data ordered by name
[(b'John', 251) (b'Mukesh', 200)]


* **Numpy.argsort() function**

 This function is used to perform an indirect sort on an input array that is, it returns an array of indices of data which is used to construct the array of sorted data

In [63]:
import numpy as np  
  
a = np.array([90, 29, 89, 12])  
  
print("Original array:\n",a)  
  
sort_ind = np.argsort(a)  
  
print("Printing indices of sorted data\n",sort_ind)  
  
sort_a = a[sort_ind]  
  
print("printing sorted array")  
  
for i in sort_ind:  
    print(a[i],end = " ")  

Original array:
 [90 29 89 12]
Printing indices of sorted data
 [3 1 2 0]
printing sorted array
12 29 89 90 

* **Numpy.lexsort() function**

 This function is used to sort the array using the sequence of keys indirectly. This function performs similarly to the numpy.argsort() which returns the array of indices of sorted data.

In [64]:
import numpy as np  
  
a = np.array(['a','b','c','d','e'])  
  
b = np.array([12, 90, 380, 12, 211])  
  
ind = np.lexsort((a,b))  
  
print("printing indices of sorted data")  
  
print(ind)  
  
print("using the indices to sort the array")  
  
for i in ind:  
    print(a[i],b[i])  


printing indices of sorted data
[0 3 1 4 2]
using the indices to sort the array
a 12
d 12
b 90
e 211
c 380


* **Numpy.nonzero() function**

 This function is used to find the location of the non-zero elements from the array.

In [65]:
import numpy as np  
  
b = np.array([12, 90, 380, 12, 211])  
  
print("printing original array",b)  
  
print("printing location of the non-zero elements")  
  
print(b.nonzero())  


printing original array [ 12  90 380  12 211]
printing location of the non-zero elements
(array([0, 1, 2, 3, 4]),)


* **Numpy.where() function**

 This function is used to return the indices of all the elements which satisfies a particular condition.

In [66]:
import numpy as np  
  
b = np.array([12, 90, 380, 12, 211])  
  
print(np.where(b>12))  
  
c = np.array([[20, 24],[21, 23]])  
  
print(np.where(c>20))

(array([1, 2, 4]),)
(array([0, 1, 1]), array([1, 0, 1]))


# NumPy Linear Algebra

Numpy provides the following functions to perform the different algebraic calculations on the input data.

* **Numpy.dot() function**

 This function is used to return the dot product of the two matrices. It is similar to the matrix multiplication. Consider the following example.

In [67]:
import numpy as np 

a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
dot = np.dot(a,b)  
print(dot)  

[[3400 6200]
 [ 374  712]]


* **Numpy.vdot() function**

 This function is used to calculate the dot product of two vectors. It can be defined as the sum of the product of corresponding elements of multi-dimensional arrays.

In [68]:
import numpy as np  

a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
vdot = np.vdot(a,b)  
print(vdot)  


5528


* **Numpy.inner() function**

 This function returns the sum of the product of inner elements of the one-dimensional array. For n-dimensional arrays, it returns the sum of the product of elements over the last axis.



In [69]:
import numpy as np 

a = np.array([1,2,3,4,5,6])  
b = np.array([23,23,12,2,1,2])  
inner = np.inner(a,b)  
print(inner)  


130


* **Numpy.matmul() function**

 It is used to return the multiplication of the two matrices. It gives an error if the shape of both matrices is not aligned for multiplication. Consider the following example.

In [70]:
import numpy as np  

a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
b = np.array([[23,23,12],[2,1,2],[7,8,9]])  
mul = np.matmul(a,b)  
print(mul)  

[[ 48  49  43]
 [144 145 112]
 [240 241 181]]


* **Numpy determinant**

 The determinant of the matrix can be calculated using the diagonal elements. The determinant of following 2 X 2 matrix can be calculated as AD - BC.

 The numpy.linalg.det() function is used to calculate the determinant of the matrix. Consider the following example.

In [71]:
import numpy as np  

a = np.array([[1,2],[3,4]])  
print(np.linalg.det(a))  

-2.0000000000000004


* **Numpy.linalg.inv() function**

 This function is used to calculate the multiplicative inverse of the input matrix. Consider the following example.

In [72]:
import numpy as np  

a = np.array([[1,2],[3,4]])  
print("Original array:\n",a)  
b = np.linalg.inv(a)  
print("Inverse:\n",b)  

Original array:
 [[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# NumPy - Copies & Views

While executing the functions, some of them return a copy of the input array, while some return the view. When the contents are physically stored in another location, it is called **Copy**. If on the other hand, a different view of the same memory content is provided, we call it as **View**.

**No Copy**

Simple assignments do not make the copy of array object. Instead, it uses the same id() of the original array to access it. The id() returns a universal identifier of Python object, similar to the pointer in C.

Furthermore, any changes in either gets reflected in the other. For example, the changing shape of one will change the shape of the other too.

In [73]:
import numpy as np 
a = np.arange(6) 

print('Our array is:') 
print(a)  

print('Applying id() function:')
print(id(a))  

print('a is assigned to b:')
b = a 
print(b)  

print('b has same id():') 
print(id(b))

print('Change shape of b:') 
b.shape = 3,2 
print(b)  

print('Shape of a also gets changed:') 
print(a)

Our array is:
[0 1 2 3 4 5]
Applying id() function:
139862401016576
a is assigned to b:
[0 1 2 3 4 5]
b has same id():
139862401016576
Change shape of b:
[[0 1]
 [2 3]
 [4 5]]
Shape of a also gets changed:
[[0 1]
 [2 3]
 [4 5]]


* **View or Shallow Copy**

 **NumPy has ndarray.view()** method which is a new array object that looks at the same data of the original array. Unlike the earlier case, change in dimensions of the new array doesn’t change dimensions of the original.

In [74]:
import numpy as np 
# To begin with, a is 3X2 array 
a = np.arange(6).reshape(3,2) 

print('Array a:') 
print(a)  

print('Create view of a:') 
b = a.view() 
print(b) 

print('id() for both the arrays are different:') 
print('id() of a:')
print(id(a))
print('id() of b:') 
print(id(b))  

# Change the shape of b. It does not change the shape of a 
b.shape = 2,3 

print('Shape of b:') 
print(b)  

print('Shape of a:')
print(a)

Array a:
[[0 1]
 [2 3]
 [4 5]]
Create view of a:
[[0 1]
 [2 3]
 [4 5]]
id() for both the arrays are different:
id() of a:
139862400959392
id() of b:
139862400956816
Shape of b:
[[0 1 2]
 [3 4 5]]
Shape of a:
[[0 1]
 [2 3]
 [4 5]]


In [75]:
import numpy as np 
# To begin with, a is 3X2 array 
a = np.arange(6).reshape(3,2) 

print('Array a:')
print(a)

print('Create view of a:') 
b = a.view() 
print(b)

print('id() for both the arrays are different:')
print('id() of a:')
print(id(a))
print('id() of b:') 
print(id(b))  

# Change the shape of b. It does not change the shape of a 
b.shape = 2,3 

print('Shape of b:') 
print(b)

print('Shape of a:')
print(a)

Array a:
[[0 1]
 [2 3]
 [4 5]]
Create view of a:
[[0 1]
 [2 3]
 [4 5]]
id() for both the arrays are different:
id() of a:
139862392096928
id() of b:
139862392098608
Shape of b:
[[0 1 2]
 [3 4 5]]
Shape of a:
[[0 1]
 [2 3]
 [4 5]]


In [76]:
import numpy as np 
a = np.array([[10,10], [2,3], [4,5]]) 

print('Our array is:') 
print(a)  

print('Create a slice:') 
s = a[:, :2] 
print(s) 

Our array is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Create a slice:
[[10 10]
 [ 2  3]
 [ 4  5]]


* **Deep Copy**

 The ndarray.copy() function creates a deep copy. It is a complete copy of the array and its data, and doesn’t share with the original array.

In [77]:
import numpy as np 
a = np.array([[10,10], [2,3], [4,5]]) 

print('Array a is:') 
print(a)

print('Create a deep copy of a:') 
b = a.copy() 
print('Array b is:') 
print(b) 

#b does not share any memory of a 
print('Can we write b is a')
print(b is a)  

print('Change the contents of b:') 
b[0,0] = 100 

print('Modified array b:')
print(b)

print('a remains unchanged:') 
print(a)

Array a is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Create a deep copy of a:
Array b is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Can we write b is a
False
Change the contents of b:
Modified array b:
[[100  10]
 [  2   3]
 [  4   5]]
a remains unchanged:
[[10 10]
 [ 2  3]
 [ 4  5]]


# Some Additional Function


* **Numpy.concatenate() fuction**

 The concatenate() function is a function from the NumPy package. This function essentially combines NumPy arrays together. This function is basically used for joining two or more arrays of the same shape along a specified axis. There are the following things which are essential to keep in mind:

 NumPy's concatenate() is not like a traditional database join. It is like stacking NumPy arrays.
This function can operate both vertically and horizontally. This means we can concatenate arrays together horizontally or vertically.


In [78]:
import numpy as np  

x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  


z=np.concatenate((x,y))  
print(z)

[[ 1  2]
 [ 3  4]
 [12 30]]


In [79]:
import numpy as np  

x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  

z=np.concatenate((x,y), axis=0)  
print(z) 

[[ 1  2]
 [ 3  4]
 [12 30]]


In [80]:
import numpy as np  

x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  

z=np.concatenate((x,y.T), axis=1)  
print(z)  

# In this example, the '.T' used to change the rows into columns and columns into rows.



[[ 1  2 12]
 [ 3  4 30]]


* **Numpy.append() function**

 The numpy.append() function is available in NumPy package. As the name suggests, append means adding something. The numpy.append() function is used to add or append new values to an existing numpy array. This function adds the new values at the end of the array.

 The numpy append() function is used to merge two arrays. It returns a new array, and the original array remains unchanged
 
 *Syntax*
 
 **numpy.append(arr, values, axis=None)**

In [81]:
import numpy as np  

a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  

c=np.append(a,b)  
print(c)  

[10 20 30 40 50 60 70 80 90 11 21 31 42 52 62 73 83 93]


In [82]:
import numpy as np  

a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  

c=np.append(a,b,axis=0)  
print(c)  

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [11 21 31]
 [42 52 62]
 [73 83 93]]


In [83]:
import numpy as np  

a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  

c=np.append(a,b,axis=1)  
print(c)  

[[10 20 30 11 21 31]
 [40 50 60 42 52 62]
 [70 80 90 73 83 93]]


# Note 

You should also understand one thing guy's always make sure that you are using numpy because numpy has bindings of C++ libraries . So wheneveryou have susuch kind  of sence kind of bindings of C amd C++ libraries usually through the operation take place very quickly .